### ISSUE TITLE
Add numeric metric: mean percentage error

### ISSUE THREAD

**Issue by datenzauberai** [tidymodels/yardstick#145]
Would it be possible to add metrics like mean percentage error to check model predictions for biases?

Compared to the current numeric metrics, it would not be possible to add a direction attribute - the optimal MPE is 0, but can be negative and positive.

I would contribute the pull request including tests and documentation if you would consider the addition.

**Comment by DavisVaughan** [comment]
"Because actual rather than absolute values of the forecast errors are used in the formula, positive and negative forecast errors can offset each other; as a result the formula can be used as a measure of the bias in the forecasts." - Wiki, about MPE

Yea this sounds like it could be useful


Regarding the direction attribute, we might need to expand the set of directions to include `"zero"` as a direction. I imagine more than just this metric would have this problem.

**Comment by datenzauberai** [comment]
Okay, I will give it a go. The `"zero"` direction would affect the tune package :-(

Comparing two metric values (including the derivate operations for a bunch of them: picking the best or sorting) could be yardstick's concern instead having it in the tune package. However, I guess that would be rather a discussion for the long time contributors :-)

**Comment by DavisVaughan** [comment]
Closed by #149
