### ISSUE TITLE
Metrics in confusion matrix consistent with caret?

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/yardstick#17]
It looks like the confusion matrix I am getting from yardstick is diagonally flipped from the one in caret. Also, the metrics like positive/negative predictive value, sensitivity/specificity, etc are all switched around.

Here's a worked example.

``` r
library(caret)
library(mlbench)
library(dplyr)
data(Sonar)

set.seed(998)
inTraining <- createDataPartition(Sonar$Class, p = .75, list = FALSE)
training <- Sonar[ inTraining,]
testing  <- Sonar[-inTraining,]

glmfit <- train(Class ~ ., data = training, 
                method = "glm", family = "binomial")

library(yardstick)

testing_results <- testing %>%
        mutate(`Logistic regression` = predict(glmfit, testing))

conf1 <- conf_mat(testing_results, truth = Class, estimate = `Logistic regression`)

conf1
#>           Truth
#> Prediction  M  R
#>          M 19 11
#>          R  8 13
summary(conf1)
#> # A tibble: 12 x 2
#>    name        value
#>    <chr>       <dbl>
#>  1 accuracy    0.627
#>  2 kappa      NA    
#>  3 sens        0.704
#>  4 spec        0.542
#>  5 prevalence  0.529
#>  6 ppv         0.633
#>  7 npv         0.619
#>  8 mcc         0.249
#>  9 j_index     0.245
#> 10 precision   0.633
#> 11 recall      0.704
#> 12 F1          0.667

confusionMatrix(testing$Class,
                predict(glmfit, testing))
#> Confusion Matrix and Statistics
#> 
#>           Reference
#> Prediction  M  R
#>          M 19  8
#>          R 11 13
#>                                           
#>                Accuracy : 0.6275          
#>                  95% CI : (0.4808, 0.7587)
#>     No Information Rate : 0.5882          
#>     P-Value [Acc > NIR] : 0.3375          
#>                                           
#>                   Kappa : 0.2471          
#>  Mcnemar's Test P-Value : 0.6464          
#>                                           
#>             Sensitivity : 0.6333          
#>             Specificity : 0.6190          
#>          Pos Pred Value : 0.7037          
#>          Neg Pred Value : 0.5417          
#>              Prevalence : 0.5882          
#>          Detection Rate : 0.3725          
#>    Detection Prevalence : 0.5294          
#>       Balanced Accuracy : 0.6262          
#>                                           
#>        'Positive' Class : M               
#> 
```

Created on 2018-02-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I started digging into the code here in this repo to see if I could find a mixup but then just decided to ask.  :grimacing:

I have the current CRAN version of caret, and I just re-installed the dev version of yardstick.

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_0.2.0    bindrcpp_0.2    yardstick_0.0.1 broom_0.4.3    
[5] dplyr_0.7.4     mlbench_2.1-1   caret_6.0-78    ggplot2_2.2.1  
[9] lattice_0.20-35
```

**Comment by topepo** [comment]
That was not deliberate. There is no standard that I know of but I'll switch them for consistency.

**Comment by topepo** [comment]
Give that a try and let me know if you have any issues. Sorry for the confusion 😜

**Comment by juliasilge** [comment]
Max, I think I may have messed up. 

If you look above, I have `caret::confusionMatrix(truth, prediction)`, which is not what that function is expecting, and is why all the specificity/sensitivity/positive/negative predictive values are mixed up. Now I am thinking *that* was my problem, everything was fine before, and *now* the `summary()` method is flipped?

**Comment by topepo** [comment]
Ah, I see. I should have caught that the arguments were switched. I try to force myself to always type the argument names although _some_  in the tidyverse group have frowned upon that since it is considered overly verbose. 

I'm not worried about the validity of the calculations from the last commit since those are checked against the expected results regardless of configuration. The choice is more about how to define the table (truth in rows or columns). 

I'll cancel the change (yay `git revert`) and go back to the original format. Sounds good?

**Comment by juliasilge** [comment]
YES. I apologize for my mixup! I'll let you close this whenever you get it all straightened back out.

**Comment by daftmath** [comment]
I'm still super confused on this. The results I get from yardstick do not match caret. When I calculate this out by hand, I get the same results from caret. The confusion matrices appear identical, but the other summary statistics are all switched around.

```
> yardstick::conf_mat(conf_df, truth=actual, estimate=predict)
          Truth
Prediction   0   1
         0 968  29
         1  23 492
```

By definition, the sensitivity (aka true positive rate) is:

TPR = TP/P = TP / (TP + FN)

Calculating by hand [from confusion matrix](https://en.wikipedia.org/wiki/Sensitivity_and_specificity#Confusion_matrix) above that would mean:

TPR = 492 / (492 + 29) = .94

Checking with caret we confirm the sensitivity is 0.94 (per caret documentation the "data" is the predicted values and "reference" is the actual values)

```
> caret::confusionMatrix(data=conf_df$predict, reference=conf_df$actual, positive = "1")
Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 968  29
         1  23 492
                                          
               Accuracy : 0.9656                               
            **Sensitivity : 0.9443**   
```

But yardstick gives the value of 0.977:

```
> summary(yardstick::conf_mat(conf_df, truth=actual, estimate=predict))
# A tibble: 14 x 2
   name                 value
   <chr>                <dbl>
 1 accuracy             0.966
 2 kappa                0.924
 **3 sens                 0.977**
```

I'm so confused that I readily admit I might be the one making a mistake, but I just cannot seem to make my hand calculated values or caret values match yardstick so something odd is going on.

**Comment by topepo** [comment]
@daftmath Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by daftmath** [comment]
I believe the confusion I was having is related to which factor level corresponds to a "positive" result. In a binary classification problem, I expected "1" to be the positive event, not "0" which is why yardstick was flipped/different compared to my hand calculations and caret.

Here's a minimal example where you can see that yardstick and caret give different results for the same data and confusion matrix. Not sure what the fix is, other than allowing a user to specify which is the positive factor.

`library(yardstick)
library(caret)

# create dummy dataset
predicted <- as.integer(c(1, 0, 1))
actual    <- as.integer(c(1, 0, 0))
df <- as.data.frame(cbind(predicted, actual))

# make sure columns are factors
df$predicted <- as.factor(df$predicted)
df$actual <- as.factor(df$actual)

# view summary with yardstick
yardstick::conf_mat(df, estimate=predicted, truth=actual)
summary(yardstick::conf_mat(df, estimate=predicted, truth=actual))

# view summary with caret
caret::confusionMatrix(data=df$predicted, reference=df$actual, positive = "1")

# Calculate sensitivity by hand
# Sensitivity = TP/P = TP / (TP + FN)
cat("Sensitivity =", 1 / (1 + 0))

**Comment by topepo** [comment]
> Not sure what the fix is, other than allowing a user to specify which is the positive factor.

Did you see the message that is created when the package is loaded? 

> library(yardstick)
> Loading required package: broom
> For binary classification, the first factor level is assumed to be the event.
> Set the global option `yardstick.event_first` to `FALSE` to change this.

Also, it is a bad idea to have factor levels with values "0" and "1". Just saying'

**Comment by azeezpok** [comment]
I am getting error in creating confusion matrix as given below. plz help me...
> conf= confusionMatrix(y_pred1, validation_set, positive = NULL,
+                 dnn = c("y_pred1", "validation_set"), prevalence = NULL)
Error: `data` and `reference` should be factors with the same levels.

**Comment by topepo** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.
