### ISSUE TITLE
Fairness metrics

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/yardstick#176]
Let's look into supporting metrics for measuring fairness for models.

- There is an [existing R package that includes such metrics](https://github.com/kozodoi/fairness).

- There are [fairness metrics in an open source library](https://github.com/IBM/AIF360) (R and Python) from IBM.

- There are definitions of [several metrics on Wikipedia](https://en.wikipedia.org/wiki/Fairness_(machine_learning)#Metrics%5B6%5D).

**Comment by juliasilge** [comment]
h2o uses some different names for some of the same metrics:

- Adverse Impact Ratio (classification)
- Standardized Mean Difference (regression)

**Comment by apreshill** [comment]
Adding fairness indicators for Tensorflow: https://github.com/tensorflow/fairness-indicators

**Comment by EmilHvitfeldt** [comment]
It might be a good idea to have some biased datasets in modeldata for examples.

One commonly used dataset is the [Boston housing dataset](https://www.kaggle.com/c/boston-housing) which includes problematic variables such as 

- black: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town.
- lstat: lower status of the population (percent).

I don't know how I feel about it ethically, but with enough documentation, it might be okay.

**Comment by EmilHvitfeldt** [comment]
I would like it if there would be some indication on the pkgdown reference page that a metric is fairness related.

**Comment by topepo** [comment]
`fairness` has different functions for different metrics. We should try to have a more general method that takes a metric set or some other metric-related argument.

**Comment by juliasilge** [comment]
The [fairmodels](https://modeloriented.github.io/fairmodels/) package computes fairness metrics based on confusion matrices and a DALEX explainer.

**Comment by skeydan** [comment]
I would say that both AI Fairness 360 and the `fairness` package (both mentioned by @juliasilge in the first comment) look very good. (By the way, they include the standard fairness datasets as well, so probably no need to have one's own?).

To me then this issue seems to be first and foremost about integration into `tidymodels`, right? (Meaning, it's a software engineering question.) 
However, there is also the question of what the metrics actually measure / hope to measure, and even though AI F 360 has good docs on that too (and a nice demo), I think one could make more explicit the underlying assumptions ...

I'll open a broader issue in a repo more appropriate for this, and hope to be linking that back here later.

@topepo @tracykteal

**Comment by topepo** [comment]
We'll work on another package for this. It will use yardstick to compute individual metrics but be another thing.
