### ISSUE TITLE
Access to class components used in macro averaging

### ISSUE THREAD

**Issue by chris-g-howden** [tidymodels/yardstick#188]
When developing multi class models it's often necessary to explore the fit for each class. One reason is that a few key classes may be more important to get right than the rest, so we want to ensure they are being fit well. 

Given that macro averaging actually calculates each classes metric would it be possible for these components to also be added to the returned object so, if necessary, people can assess each class? 

I think it would help alot of people, some papers seem to expect these class specific metrics.

**Comment by topepo** [comment]
Unless @DavisVaughan feels differently, I don't think that we would extend the structure of the return objects for this feature (since we would have to include a `class` column for this specific measure. 

You can get what you want by [using this code](https://www.tmwr.org/performance.html#multi-class-classification-metrics) to compute the measures and get their relative weights.

**Comment by chris-g-howden** [comment]
Thanks, that code works for sentivity and could be used as a template for the others. I have since found that the caret package calculates within class metrics, so between that and the overall class metrics your package supplies I can get what I need without coding things up from scratch!
