### ISSUE TITLE
Bias variance decomposition function?

### ISSUE THREAD

**Issue by amcmahon17** [tidymodels/yardstick#269]
Hello,
yardstick is already tremendous, but I do have a feature request. There is a python function in the mlxtend that gives an estimated bias variance decomposition function for models via a boostrap. Is it possible to add this kind of functionality in yardstick?

It might not be practical or wise to add, but I often find myself wanting it. Thank you.

Example:
http://rasbt.github.io/mlxtend/user_guide/evaluate/bias_variance_decomp/

**Comment by DavisVaughan** [comment]
It seems like you actually have to fit a model multiple times with bootstrapped resamples to generate these results right?

This doesn't seem quite right for yardstick, because yardstick won't ever be in the business of fitting models, but it seems like it could be some combination of parsnip, rsample, and some function to compute the bias/variance metric

I think those are best suited for a separate package!

**Comment by amcmahon17** [comment]
Yes, you're right ---I stand corrected. It is certainly a complicated enough task to live in a separate package, housed with I don't know what else...
