### ISSUE TITLE
one versus all

### ISSUE THREAD

**Issue by topepo** [tidymodels/yardstick#4]
make a function to get all the two-class statistics when there are 3+ levels (`one_v_all`)

**Comment by DavisVaughan** [comment]
I'm not sure we need this since you can just use macro/micro averaging for this case now. Some probability metrics do use `yardstick:::one_vs_all_impl` which essentially does this, but I don't know if it would be useful to expose this or not. It would have to be cleaned up and made more general for use with other class metrics. I'll leave that up to you

**Comment by DavisVaughan** [comment]
I think I'm going to close in favor of revisiting later if we have a true use case for it
