### ISSUE TITLE
yardstick

### ISSUE THREAD

**Issue by mawardivaz** [tidymodels/yardstick#409]
Error in `yardstick_table()`:
! `truth` must have at least 2 factor levels.
ℹ This is an internal error that was detected in the yardstick package.

Error in yardstick_table(truth = truth, estimate = estimate, case_weights = case_weights) :
11.
stop(fallback)
10.
signal_abort(cnd, .file)
9.
abort("`truth` must have at least 2 factor levels.", .internal = TRUE)
8.
yardstick_table(truth = truth, estimate = estimate, case_weights = case_weights)
7.
conf_mat.data.frame(., Smear_done, .pred_class)
6.
conf_mat(., Smear_done, .pred_class)
5.
pluck_raw(.x, list2(...), .default = .default)
4.
pluck(., 1)
3.
as_tibble(.)
2.
ggplot(., aes(Prediction, Truth, alpha = n))
1.
predictions_glm %>% conf_mat(Smear_done, .pred_class) %>% pluck(1) %>%
as_tibble() %>% ggplot(aes(Prediction, Truth, alpha = n))

**Comment by EmilHvitfeldt** [comment]
Hello @mawardivaz  👋 

Thanks for raising this issue! without the data it can be hard to see what the problem is. Nevertheless, it appears that `.Smear_done` or `.pred_class` has fewer than 2 levels.

You can check that by running the following code:

```r
predictions_glm %>%
  dplyr::select(Smear_done, .pred_class) %>%
  lapply(levels)
```

the output will tell you the levels of `.Smear_done` and `.pred_class`. They should be the same and have 2 or more levels

**Comment by mawardivaz** [comment]
Hi @EmilHvitfeldt 

Thank you for the answer.  Yes the  .Smear_done or .pred_class has fewer than 2 levels. I then got the solution.
