### ISSUE TITLE
Add modified correlation statistic? 

### ISSUE THREAD

**Issue by topepo** [tidymodels/yardstick#87]
The [Ideality of Correlation statistic](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=%22Ideality+of+Correlation%22&btnG=) is something that comp chemists seem to like (I guess RMSE isn't good enough for them). We might think about adding that. 

![image](https://user-images.githubusercontent.com/5731043/53191777-b78b1980-35da-11e9-981e-84daadeb980d.png)

**Comment by DavisVaughan** [comment]
What is r?

**Comment by topepo** [comment]
I think it is the regular old correlation statistic between the observed and predicted values.

**Comment by DavisVaughan** [comment]
If you choose to take on this metric at TDD:

* I would use `mae()` as a general guide.

- [ ] Call it `iic()`

- [ ] Pay close attention to how we generate documentation and examples automatically

- [ ] Try and understand how `metric_summarizer()` works, along with the rationale behind `metric_vec_template()`, then use them in the implementation.

- [ ] Add a few tests. Small examples you can match from academic papers are best, but otherwise any online example is okay. If all else fails, create an example "by hand" that is easy to manually compute the result for.

- [ ] Use the file naming scheme `num-<metric>.R`
